# Custom Language File for Launcher Customizer

[ejs.app]
title = "Zone-Arc"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "ZONE-ARC ROLEPLAY"
welcomeDescription = "Coming son.."
welcomeDescCTA = "Projet en développement"
